export const categories = [
  { key: "vegetables", label: "🥦 채소류" },
  { key: "fruits", label: "🍎 과일류" },
  { key: "dairy", label: "🥛 유제품" },
  { key: "meat", label: "🥩 육류" },
  { key: "seafood", label: "🐟 해산물" },
  { key: "fermented", label: "🧂 발효식품/젓갈" },
  { key: "grains", label: "🍞 빵/곡물" },
  { key: "condiments", label: "🍯 소스/조미료" },
  { key: "processed", label: "🥫 가공식품" },
  { key: "beverages", label: "🍵 음료" },
  { key: "desserts", label: "🍰 디저트" },
  { key: "frozen", label: "❄️ 냉동식품" },
  { key: "supplements", label: "💊 건강식품/보조제" },
  { key: "baby", label: "🍼 이유식/아기용품" },
];